version: 2
jobs:
  build-custom-docker-image:
    docker:
      - image: docker:git
    steps:
      - checkout
      # To enable `docker` command and `docker-compose` command on Docker Executor
      # https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker
      - run:
          name: Build custom Docker image
          command: |
            set -x
            docker build -t quay.io/nobuoka/circleci-custom-image-example custom-docker-image
      - run:
          name: Push custom Docker image
          command: |
            set -x
            sh +x -c 'echo $QUAY_TOKEN' | docker login -u=$QUAY_USERNAME --password-stdin quay.io
            docker push quay.io/nobuoka/circleci-custom-image-example
  run-on-custom-docker-image:
    docker:
      - image: quay.io/nobuoka/circleci-custom-image-example
    steps:
      - checkout
      - run:
          name: Run shell script
          command: |
            set -x
            /example/hello.sh
workflows:
  version: 2
  build-and-run:
    jobs:
      - build-custom-docker-image:
          context: org-global
      - run-on-custom-docker-image:
          requires:
            - build-custom-docker-image
